# SiktirGitDPI preset - TurkNet.
#
# TurkNet'in DPI'si goreceli olarak basit. Tek basina TLS split + http
# mangle yeterli. Daha agresif baypas icin disorder + fake-ttl deneyin.

strategies       = tls-split,wrong-chksum,http-mangle
tls_split_mode   = midsni
fake_ttl         = 0
http_mangle_case = true
ports            = 80,443
log_level        = info
inbound_rst_drop = true
flow_tracking    = true
